language: python
matrix:
  include:
    - python: 3.7
      dist: focal
      sudo: true
    - python: 3.8
      dist: focal
      sudo: true
    - python: 3.9
      dist: focal
      sudo: true
install: 
  - pip install tox-travis
  - pip install coveralls
script: tox

after_success:
    coveralls
